HW02 is completed
RacovAlex/homework-basic pull request #1
Opened 2024-08-20 10:32 UTC by RacovAlex

## Домашнее задание №2 «Чиним, собираем и запускаем приложение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Приложение локально собирается
- [ ] Линтер не выдает ошибок при локальном запуске

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла

#### Зачёт от 4 баллов

2024-08-20 14:21 UTC, alecchepkin requested changes
Неплохо. Но нужно обрабоать ошибки

2024-08-20 14:21 UTC, alecchepkin commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
если ошибка нужно вернуть ошибку

2024-08-20 14:21 UTC, alecchepkin commented on hw02_fix_app/main.go
> +	staff, err = reader.ReadJSON(path)
нужно обработать ошибку

2024-08-20 14:21 UTC, alecchepkin commented on hw02_fix_app/main.go
>  	fmt.Scanln(&path)
нужно проверить на ошибку

2024-08-21 12:13 UTC, alecchepkin commented
Все норм. Аппрувд

2024-08-21 12:20 UTC, RacovAlex commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
исправлено

2024-08-21 12:20 UTC, alecchepkin approved these changes
10 балов

2024-08-21 12:21 UTC, merged