HW04 is completed
RacovAlex/homework-basic pull request #3
Opened 2024-08-31 10:43 UTC by RacovAlex

## Домашнее задание №4 «Компаратор структур»

- Реализуйте структуру Book со следующими неэкспортируемыми полями: ID, Title, Author, Year, Size, Rate (может быть дробным).
- Реализуйте методы для установки и получения полей структуры
- Реализуйте структуру с методом позволяющим сравнивать книги по полям Year, Size, Rate. Выбор режима сравнения задается в конструкторе структуры через перечисление (enum). Метод принимает 2 книги и выдает true если первый аргумент больше второго и false если наоборот.
- Обратите внимание на value и pointer ресиверы

### Критерии оценки
- Пайплайн зелёный - 4 балла
- Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-08-31 20:48 UTC, alecchepkin requested changes
Отлично. Но если вынести наши комонетны в отдельные пакеты, то в main уже не получилось так создвать Book и BookComporator. Предлагаю использовать конструкторы для них.

2024-08-31 20:48 UTC, alecchepkin commented on hw04_struct_comparator/go.mod
>  module github.com/fixme_my_friend/hw04_struct_comparator
Название пакет нужно исправить

2024-08-31 20:48 UTC, alecchepkin commented on hw04_struct_comparator/main.go
> +	bookComparator := BookComparator{comparator: CompareByRate}
тоже и для компорейтора, лучше созадать констуктор. Если расположить BookComporator в отдельный пакет то так уже не получиться задать ему тип сравнения.

2024-08-31 20:48 UTC, alecchepkin commented on hw04_struct_comparator/main.go
> +type Comparator int
идеоматичне называть с таким же префиксом, котрый будет и у констант

```suggestion
type Compare int

const (
	CompareByYear Comparator = iota
	CompareBySize
	CompareByRate
)
```

2024-08-31 20:48 UTC, alecchepkin commented on hw04_struct_comparator/go.mod
> -go 1.20
желательно использовать самую последнию версию go

2024-08-31 20:48 UTC, alecchepkin commented on hw04_struct_comparator/main.go
> +	}
У Book приветные свойства, поэтому коректней создавать с помощью конструктора и менять через сеттеры.

2024-08-31 20:52 UTC, alecchepkin commented on hw04_struct_comparator/main.go
> +// enum компараторов
Я бы сказал это тип, режим сравнея для компоратора. Т.к. компоратор у нас по сути один, но меняется логика сравнения.

2024-09-01 06:22 UTC, RacovAlex commented on hw04_struct_comparator/go.mod
> -go 1.20
после изменения на версию установленную у меня 1.22 выползает такое сообщение: go: module hw04_struct_comparator listed in go.work file requires go >= 1.22, but go.work lists go 1.20; to update it:
go work use. Безопасно ли просто взять и поменять версию?

2024-09-01 07:22 UTC, RacovAlex commented on hw04_struct_comparator/main.go
> +	}
Исправил, но мне не понятно, если я буду использовать создание экземпляра структуры из другого пакета и при этом в конструкторе должен указать все переменные структуры и в правильной последовательности, как я могу это сделать, если я их не знаю, они для меня приватные. Или это должно быть в описании конструктора?

2024-09-01 07:39 UTC, alecchepkin commented on hw04_struct_comparator/go.mod
> -go 1.20
Да совершенно безопастно. Нужно просто поменять версию в `go.work` на 1.22 тоже

2024-09-01 07:52 UTC, alecchepkin commented on hw04_struct_comparator/main.go
> +	}
Да в констукторе по именам агруметов можно понять что передавать в какой последовательности. Но это не очень удобно когда столько много параметров в констукторе. Их действительно нужно передавать в правильно порядке. Особенно это касается параметров с одинковым типом. Можно легко перепутать. Для этого можно применять внутреннию валидацию например.

Можно переделать реализацию и сделать BookBuilder

```
book := NewBookBuilder().
	SetID(1).
	SetTitle("Go Programming").
	SetAuthor("John Doe").
	SetYear(2023).
	SetSize(300).
	SetRate(4.5).
	Build()
```

2024-09-01 11:53 UTC, alecchepkin approved these changes

2024-09-01 11:57 UTC, merged