HW05 is completed
RacovAlex/homework-basic pull request #4
Opened 2024-09-07 09:52 UTC by RacovAlex

## Домашнее задание №5 «Подсчет площади геометрических фигур»

- Создайте интерфейс Shape, который будет иметь метод для вычисления площади.

- Реализуйте структуры для геометрических фигур: круг, прямоугольник, треугольник. Каждая структура должна реализовывать интерфейс Shape.

- Создайте функцию calculateArea(s any), которая ожидает на входе объект типа Shape и возвращает его площадь. Если переданный объект не реализует интерфейс Shape, функция должна вернуть ошибку.

- В функции main создайте несколько объектов разных типов (круг, прямоугольник, треугольник) и вызвать функцию calculateArea для каждого из них. Обработайте возможные ошибки и выведите результаты подсчета площадей на экран.

Пример результата работы программы:

Круг: радиус 5 Площадь: 78.53981633974483

Прямоугольник: ширина 10, высота 5 Площадь: 50

Треугольник: основание 8, высота 6 Площадь: 24

Ошибка: переданный объект не является фигурой.

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~80 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-09-07 12:11 UTC, alecchepkin requested changes
Можно еще более усложнить задание после. Перенести интерфейс в package figure и сделать все реализации приватными.

2024-09-07 12:11 UTC, alecchepkin commented on hw05_shapes/main.go
> +		fmt.Printf("Круг: радиус %f Площадь: %f\n", a.Radius, area)
слишком много подробностей мы должны знать о каждом объекте. Эти знания нужно перенести в сами структуры. Предлагаю добавить интефейс метод `Print()`.
И тогда можно избавиться от функции `PrintFigureWithArea`

2024-09-08 11:04 UTC, alecchepkin approved these changes
Отлично 10/10

2024-09-08 11:04 UTC, alecchepkin commented on hw05_shapes/main.go
> +		return 0, errors.New("ошибка: переданный объект не является фигурой")
слово ошибка можно не писать

2024-09-08 18:29 UTC, RacovAlex commented on hw05_shapes/main.go
> +		return 0, errors.New("ошибка: переданный объект не является фигурой")
согласен, но написал, т.к. это было условие задачи

2024-09-09 08:33 UTC, merged