HW09 is completed
RacovAlex/homework-basic pull request #8
Opened 2024-10-03 16:20 UTC by RacovAlex

## Домашнее задание №9 «JSON и Pb сериализация»
- Реализуйте структуру Book со следующими полями: ID, Title, Author, Year, Size, Rate (может быть дробным).
- Реализуйте для нее интерфейсы Marshaller и Unmarshaller  из пакета json.
- Составьте protobuf спецификацию для Book
- Реализуйте для нее интерфейс Message из пакета proto.
- Напишите фукции выполняющие сериализацию/десериализацию слайса объектов. 
- Напишите юнит тесты на реализованные функции;

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~100 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-10-05 13:07 UTC, alecchepkin requested changes

2024-10-05 13:07 UTC, alecchepkin commented on hw09_serialize/entity/book.go
> +func validStruct(year, size int, rate float64) error {
я бы передал все структуру Book и уже внутри бы валидировал поля которые нужно чекнуть.

2024-10-05 13:07 UTC, alecchepkin commented on hw09_serialize/entity/book.go
> +func SliceToBytesMarshalJSON(s []*Book) ([][]byte, error) {
Мы должны получить масив байтов а не массив массивом байтов

2024-10-08 14:11 UTC, RacovAlex commented on hw09_serialize/entity/book.go
> +	temp := struct {
Не получается, вызывается рекурсия анмаршалинга JSON. Предложил в коде вариант с алиасом

2024-10-09 08:01 UTC, alecchepkin approved these changes

2024-10-09 08:42 UTC, merged